version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: performance_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  golang-api:
    build: ./golang-api
    container_name: golang_api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: performance_test
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - app-network

  nestjs-api:
    build: ./nestjs-api
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: performance_test
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - app-network

  python-api:
    build: ./python-api
    container_name: python_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: performance_test
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - app-network

  dotnet-api:
    build: ./dotnet-api
    container_name: dotnet_api
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=performance_test;Username=postgres;Password=password"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 